; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino

; Vitesse du moniteur série pour les l'affichage des logs (Serial.print)
monitor_speed = 115200
upload_port = COM8

; Gestion automatique des bibliothèques nécessaires
lib_deps =
    m5stack/M5Unified @ ^0.1.17
    m5stack/M5CoreS3 @ ^1.0.0
    m5stack/M5GFX @ ^0.1.15
    lvgl/lvgl @ ^8.4.0

; Configuration matérielle spécifique à l'ESP32-S3 pour l'USB natif
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MSC_ON_BOOT=0
    -D ARDUINO_USB_MODE=0
    -D LV_CONF_INCLUDE_SIMPLE
    -I src

    ; --- CORRECTIF POUR LES ANIMATIONS SQUARELINE (user_data) ---
    -D LV_USE_ANIM_CUSTOM_USER_DATA=1  ; Force LVGL à accepter les données d'animation
        -DBOARD_HAS_PSRAM
    -D LV_USE_USER_DATA=1
    ; Forcer le mode de mémoire spécifique du CoreS3 (OPI PSRAM)
    -D CONFIG_SPIRAM_MODE_OCT=1
    -D CONFIG_SPIRAM_SPEED_80M=1